#!/usr/bin/expect -f

set timeout 3600

set src_file [lindex $argv 0]
set dst_file [lindex $argv 1]

set password "abcd" 

spawn scp -r $src_file $dst_file  

expect {  
 "(yes/no)?" {  
   send "yes\n"  
   expect "*assword:" { send "$password\n"}  
  }  
  "*assword:" {  
   send "$password\n"  
  }  
}  
expect "100%"  
expect eof  
